#!/bin/sh
set -e

# Remove symlink
rm -f /usr/bin/indiamart-scraper

# Update Desktop entry database
if [ -x "$(command -v update-desktop-database)" ]; then
    update-desktop-database -q /usr/share/applications || true
fi

# Update system icon cache
if [ -x "$(command -v gtk-update-icon-cache)" ]; then
    gtk-update-icon-cache -f -t /usr/share/icons/hicolor || true
fi

exit 0
